package main

import (
	"fmt"
	"github.com/DouFuJuShi/protoc-gen-go-gin/template"
	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
	"net/http"
)

const (
	GeneratedFilenameSuffix = "_gin.pb.go"
	ctxPKG                  = protogen.GoImportPath("context")
	ginPKG                  = protogen.GoImportPath("github.com/gin-gonic/gin")
	errsPKG                 = protogen.GoImportPath("errors")
	metaPKG                 = protogen.GoImportPath("google.golang.org/grpc/metadata")
	httpPKG                 = protogen.GoImportPath("net/http")
)

type GeneratedFile struct {
	in  *protogen.File
	out *protogen.GeneratedFile
}

func (g GeneratedFile) before() {
	g.out.P("// Code generated by protoc-gen-go-gin. DO NOT EDIT.\"")
	g.out.P()
	g.out.P("package ", g.in.GoPackageName)
	g.out.P()

	// 这里是为了程序编译的时候确保这些包是正确的
	g.out.P("// ", ctxPKG.Ident(""))
	g.out.P("// ", ginPKG.Ident(""))
	g.out.P("// ", errsPKG.Ident(""))
	g.out.P("// ", httpPKG.Ident(""))
	g.out.P("// ", metaPKG.Ident(""))
	g.out.P()
}

func (g GeneratedFile) after() {

}

func (g GeneratedFile) genService(s *protogen.Service) {
	st := template.ServiceTemplate{
		Name: s.GoName,
	}

	for _, m := range s.Methods {
		httpRule, ok := proto.GetExtension(m.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if !ok || httpRule == nil {
			continue
		}

		var (
			path   string
			method string
		)
		switch pattern := httpRule.Pattern.(type) {
		case *annotations.HttpRule_Get:
			path = pattern.Get
			method = http.MethodGet
		case *annotations.HttpRule_Put:
			path = pattern.Put
			method = http.MethodPut
		case *annotations.HttpRule_Post:
			path = pattern.Post
			method = http.MethodPost
		case *annotations.HttpRule_Delete:
			path = pattern.Delete
			method = http.MethodDelete
		case *annotations.HttpRule_Patch:
			path = pattern.Patch
			method = http.MethodPatch
		case *annotations.HttpRule_Custom:
			path = pattern.Custom.Path
			method = pattern.Custom.Kind
		}

		var request = m.Input.GoIdent.GoName
		if m.Input.Desc.FullName() == "google.protobuf.Empty" {
			request = ""
		}

		var reply = m.Output.GoIdent.GoName
		if m.Output.Desc.FullName() == "google.protobuf.Empty" {
			reply = ""
		}

		st.AddMethod(&template.MethodTemplate{
			Name:       m.GoName,
			Request:    request,
			Reply:      reply,
			Path:       path,
			HttpMethod: method,
		})
	}

	g.out.P(st.String())
}

func (g GeneratedFile) Exec() error {
	g.before()

	if len(g.in.Services) == 0 {
		return nil
	}

	for _, s := range g.in.Services {
		g.genService(s)
	}

	g.after()
	return nil
}

func NewGeneratedFile(plugin *protogen.Plugin, in *protogen.File) *GeneratedFile {
	generatedFileName := fmt.Sprintf("%s%s", in.GeneratedFilenamePrefix, GeneratedFilenameSuffix)
	return &GeneratedFile{
		in:  in,
		out: plugin.NewGeneratedFile(generatedFileName, in.GoImportPath),
	}
}

func Handler() func(plugin *protogen.Plugin) error {
	return func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			NewGeneratedFile(plugin, file).Exec()
		}
		return nil
	}
}
