// Code generated by protoc-gen-go-gin. DO NOT EDIT."

package v1

import (
	context "context"
	errors "errors"
	gin "github.com/gin-gonic/gin"
	metadata "google.golang.org/grpc/metadata"
)

// context.metadata.
// gin.errors.
type UserHTTPServer interface {
	GetInfo(context.Context, *UserRequest) (*UserReply, error)
}

func RegisterUserHTTPServer(router gin.IRouter, srv UserHTTPServer) {

	router.GET("/v1/user/info", func(c *gin.Context) {
		var in UserRequest
		fmt.Println(in)
	})

}
